module Test

# THIS FILE IS AUTOGENERATED

import "./float-tests.rl";
import "./list-tests.rl";
import "./encryption-module-tests.rl";
import "./type-tests.rl";
import "./intrinsics-tests.rl";
import "./if-tests.rl";
import "./import-tests.rl";
import "./char-tests.rl";
import "./fn-test.rl";
import "./enum-tests.rl";
import "./char-module-tests.rl";
import "./class-tests.rl";
import "./tuple-tests.rl";
import "./while-loops-tests.rl";
import "./foreach-loop-tests.rl";
import "./option-tests.rl";
import "./io-module-tests.rl";
import "./int-tests.rl";
import "./for-loops-tests.rl";

fn main() {
    let should_print = true;
    let crash_on_failure = true;
    FloatTests::run(should_print, crash_on_failure);
    ListTests::run(should_print, crash_on_failure);
    EncryptionModuleTests::run(should_print, crash_on_failure);
    TypeTests::run(should_print, crash_on_failure);
    IntrinsicsTests::run(should_print, crash_on_failure);
    IfTests::run(should_print, crash_on_failure);
    ImportTests::run(should_print, crash_on_failure);
    CharTests::run(should_print, crash_on_failure);
    FnTests::run(should_print, crash_on_failure);
    EnumTests::run(should_print, crash_on_failure);
    CharModuleTests::run(should_print, crash_on_failure);
    ClassTests::run(should_print, crash_on_failure);
    TupleTests::run(should_print, crash_on_failure);
    WhileLoopTests::run(should_print, crash_on_failure);
    ForeachLoopTests::run(should_print, crash_on_failure);
    OptionTests::run(should_print, crash_on_failure);
    IOModuleTests::run(should_print, crash_on_failure);
    IntTests::run(should_print, crash_on_failure);
    ForLoopTests::run(should_print, crash_on_failure);
}

main();