# Automatically generated by premake.py
CC := /usr/bin/x86_64-pc-linux-gnu-gcc
CFLAGS := -Iinclude -ggdb -O2 -Wall -Wextra -std=gnu17 -Wshadow -Wconversion -Wsign-conversion -Wunused -Wuninitialized -Wstrict-prototypes -Wmissing-prototypes -Wmissing-declarations -Wredundant-decls -Wfloat-equal -Wdouble-promotion -Wformat=2 -Wformat-truncation -Wformat-overflow -Wundef -Wcast-align -Wcast-qual -Wpointer-arith -fstack-protector-strong -D_FORTIFY_SOURCE=2 -pipe -march=native
DEBUG_FLAGS := -O0 -g3
PREFIX := /usr/local
