name: CMake on a single platform

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  release:
    types: [ created ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Configure CMake
        run: cmake -B build -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }}

      - name: Build
        run: cmake --build build --config ${BUILD_TYPE}

      - name: Create Tarballs
        run: |
          tar -czvf EARL-${{ github.sha }}-linux.tar.gz -C build .

      - name: Upload Tarball as Artifact
        uses: actions/upload-artifact@v3
        with:
          name: tarball
          path: EARL-${{ github.sha }}-linux.tar.gz

  upload:
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'release'
    steps:
      - name: Download Tarball Artifact
        uses: actions/download-artifact@v3
        with:
          name: tarball

      - name: Upload Release Assets
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: EARL-${{ github.sha }}-linux.tar.gz
          asset_name: EARL-${{ github.sha }}-linux.tar.gz
          asset_content_type: application/gzip
