name: Build and Release

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up C++
        uses: actions/setup-cpp@v2

      - name: Build
        run: |
          mkdir build
          cd build
          cmake -S .. -B .
          make

      - name: Create Tarballs
        run: |
          tar -czvf ../EARL-${{ github.event.release.tag }}-linux.tar.gz ../

      - name: Upload Release Assets
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: EARL-${{ github.event.release.tag }}-linux.tar.gz
          asset_name: EARL-${{ github.event.release.tag }}-linux.tar.gz
          asset_content_type: application/gzip
